apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
spec:
  destination:
    namespace: backend
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://github.com/Lapin-Learn/infrastructure"
    path: k8s
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
