apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend
  labels:
    app: backend-deployment
  annotations:
    argocd-image-updater.argoproj.io/image-list: "duyquan/backend-main-server"
    argocd-image-updater.argoproj.io/backend-main-server.update-strategy: "semver"
    argocd-image-updater.argoproj.io/backend-main-server.allow-tags: "production-*"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: main-api
          image: duyquan/backend-main-server:production-f9a1c4ac74f66088c298cc7e916a914d56511006
          envFrom:
            - secretRef:
                name: backend-secret
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
