apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-lapinlearn
  namespace: backend
spec:
  dnsNames:
    - api.lapinlearn.edu.vn
  secretName: api-lapinlearn-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: preview-api-lapinlearn
  namespace: backend
spec:
  dnsNames:
    - preview-api.lapinlearn.edu.vn
  secretName: preview-api-lapinlearn-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
