apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: patroni
spec:
  serviceName: patroni-service
  replicas: 3 # 1 leader + 2 followers
  selector:
    matchLabels:
      app: patroni
  template:
    metadata:
      labels:
        app: patroni
    spec:
      containers:
        - name: postgres
          image: ghcr.io/zalando/spilo-15:latest # Patroni-based PostgreSQL image
          ports:
            - containerPort: 5432 # PostgreSQL
            - containerPort: 8008 # Patroni REST API
          env:
            - name: PATRONI_SCOPE
              value: patroni-cluster
            - name: PATRONI_NAMESPACE
              value: /service/
            - name: PATRONI_RESTAPI_LISTEN
              value: "0.0.0.0:8008"
            - name: PATRONI_POSTGRESQL_LISTEN
              value: "0.0.0.0:5432"
            - name: PATRONI_SUPERUSER_USERNAME
              value: postgres
            - name: PATRONI_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: patroni-secret
                  key: POSTGRES_SUPERUSER_PASSWORD
            - name: PATRONI_REPLICATION_USERNAME
              value: replicator
            - name: PATRONI_REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: patroni-secret
                  key: POSTGRES_REPLICATION_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: patroni-storage
      volumes:
        - name: patroni-storage
          persistentVolumeClaim:
            claimName: patroni-pvc
