- name: Deploy Bitnami PostgreSQL with Replication
  hosts: localhost
  gather_facts: false
  vars_files:
    - secrets.yml
  tasks:
    - name: Add Bitnami Helm Repository
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami

    - name: Create Kubernetes Secret for PostgreSQL
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: postgres-secret
            namespace: database
          type: Opaque
          data:
            postgres-password: "{{ postgres_password | b64encode }}"
            replication-password: "{{ replication_password | b64encode }}"

    - name: Deploy Bitnami PostgreSQL with Replication
      kubernetes.core.helm:
        name: postgresql
        chart_ref: bitnami/postgresql
        release_namespace: database
        state: present
        values:
          architecture: "replication"
          auth:
            username: postgres
            database: lapinlearn
            existingSecret: postgres-secret
            replicationUsername: replica
            replicationPassword: "{{ replication_password }}"
          primary:
            persistence:
              size: 10Gi
          readReplicas:
            replicaCount: 1
