- hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Add Prometheus Helm repository
      kubernetes.core.helm_repository:
        repo_name: prometheus-community
        repo_url: https://prometheus-community.github.io/helm-charts
        state: present

    - name: Install Prometheus
      kubernetes.core.helm:
        kubeconfig: "{{ kubeconfig }}"
        name: prometheus
        chart_ref: prometheus-community/prometheus
        release_namespace: monitoring
        create_namespace: true

    - name: Add Grafana Helm repository
      kubernetes.core.helm_repository:
        repo_name: grafana
        repo_url: https://grafana.github.io/helm-charts
        state: present

    - name: Install Grafana
      kubernetes.core.helm:
        kubeconfig: "{{ kubeconfig }}"
        name: grafana
        chart_ref: grafana/grafana
        release_namespace: monitoring
        create_namespace: true
