- hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Install NGINX Ingress Controller
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition: "{{ lookup('url', nginx_ingress_url, split_lines=False) }}"
