- hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yaml
  tasks:
    - name: Add Jetstack Helm repository
      kubernetes.core.helm_repository:
        repo_name: jetstack
        repo_url: https://charts.jetstack.io
        state: present

    - name: Install Cert-Manager
      community.kubernetes.helm:
        kubeconfig: "{{ kubeconfig }}"
        name: cert-manager
        chart_ref: jetstack/cert-manager
        release_namespace: cert-manager
        create_namespace: true
        values:
          installCRDs: true
