- import_playbook: install-nginx-ingress.yml
- import_playbook: install-cert-manager.yml
- import_playbook: install-monitoring.yml
- import_playbook: install-argocd.yml
- import_playbook: install-metrics-server.yml
- import_playbook: install-postgres.yml
